ALTER TABLE USERS
    ALTER COLUMN password_hash TYPE BYTEA USING password_hash::bytea,
    ALTER COLUMN password_hash SET NOT NULL,
    ADD COLUMN IF NOT EXISTS profile_url TEXT ,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();