BEGIN;

ALTER TABLE DOCUMENTS DROP CONSTRAINT fk_user;
ALTER TABLE USERS DROP CONSTRAINT users_pkey;

ALTER TABLE USERS
    ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE DOCUMENTS 
    ALTER COLUMN user_id TYPE BIGINT;

ALTER TABLE USERS ADD PRIMARY KEY (user_id);
ALTER TABLE DOCUMENTS ADD CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES USERS(user_id);

COMMIT;